### ISSUE TITLE
Add support to .NET 8

### ISSUE THREAD

**Issue by InCerryGit** [Hitmasu/Jitex#95]
.NET 8 has been officially released, and I upgraded my project to .NET 8 yesterday. I've found that Jitex throws an error and doesn't work. Is there a plan to support .NET 8, and if so, when can we expect it to be implemented?

**Comment by Hitmasu** [comment]
I hope none "breakchanges" on .NET 8... I'll probably release a new version until the end of month.

**Comment by Hitmasu** [comment]
Sorry for the delay.

Tomorrow I plan to release the version containing .NET 8.0 along with the 32-bit version.
